Features/stylist datetime selection
JustTory/barberino_fe pull request #2
Opened 2022-07-17 12:34 UTC by quantriminh

2022-07-17 12:38 UTC, tranngminhdao commented on src/component/bookingStep/bookingFooter.jsx
> +);
Good

2022-07-17 12:50 UTC, tranngminhdao requested changes
Complete API request before merging

2022-07-17 14:18 UTC, quantriminh commented
Ack, waiting for the BE dev to finalize the API parameters

2022-07-19 06:24 UTC, tranngminhdao commented on src/component/bookingStep/index.jsx
>              setSelectedDateTime={setSelectedDateTime}
Can we combine all state in step2 data

2022-07-19 06:55 UTC, tranngminhdao requested changes
Nested state mistake in the StepDateTime and StepServices. The father component is passing state to children, use that state, don't create another internal state

2022-07-21 08:54 UTC, tranngminhdao requested changes
Using a react-select library for the frontend customization

<img width="544" alt="image" src="https://user-images.githubusercontent.com/107382512/180173328-d62448c4-390e-4c9b-9490-06376502bb45.png">

2022-07-21 08:54 UTC, tranngminhdao commented on src/component/bookingStep/index.jsx
> +      const isValid = validateStepOne(information);
Don't need to pass information params anymore

2022-07-21 08:54 UTC, tranngminhdao commented on src/component/bookingStep/step/stepDateTime.jsx
> +            {stylists !== undefined &&
Just need to write stylists && stylists.map(.....

2022-07-24 06:05 UTC, merged